pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Starting Build'
                sh 'python3 --version'
            }
        }
        stage('Test') {
            steps {
                echo 'Starting Test'
                sh 'python --version'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Starting Deploy'
            }
        }
    }
}