pipeline {
    agent any
    stages {
        stage('Setup Virtual Environment') {
            steps {
                sh '''
                cd home/duc
                mkdir test
                cd test
                python3 -m venv venv
                source venv/bin/activate
                pip install Scrapy
                '''
            }
        }
        stage('Run Python Script') {
            steps {
                sh '''
                cd home/duc/test
                source venv/bin/activate
                Scrapy -V
                '''
            }
        }
    }
}